// <auto-generated />
using Company.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Company.DAL.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20230428151037_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Company.DAL.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("numeric");

                    b.Property<string>("Evaluation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = 5000m,
                            Evaluation = "Good",
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 2,
                            Budget = 10000m,
                            Evaluation = "Moderate",
                            Name = "Marketing"
                        });
                });

            modelBuilder.Entity("Company.DAL.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Name = "Khaled"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Name = "Mohamed"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Name = "Ali"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Name = "Ahmed"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            Name = "Eslam"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 2,
                            Name = "Omar"
                        });
                });

            modelBuilder.Entity("Company.DAL.Employee", b =>
                {
                    b.HasOne("Company.DAL.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Company.DAL.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
